<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
      <OutputType>Exe</OutputType>
      <TargetFramework>net8.0</TargetFramework>
      <ImplicitUsings>enable</ImplicitUsings>
      <Nullable>enable</Nullable>
      <RithmicRapiDll Condition="'$(RithmicRapiDll)' == ''">$(RITHMIC_RAPI_DLL)</RithmicRapiDll>
    </PropertyGroup>
    <ItemGroup>
      <Reference Include="rapiplus" Condition="'$(RithmicRapiDll)' != ''">
        <HintPath>$(RithmicRapiDll)</HintPath>
        <Private>false</Private>
      </Reference>
    </ItemGroup>
</Project>
